version: v1
env: prod

registry: richardholzeis/
pullPolicy: Always

ingress:
  host: holzeis.par01.containers.appdomain.cloud
  secret: holzeis

vapid:
  publicKey: 
  privateKey: 

jwt:
  secret: 

couchdb:
  clusterSize: 1
  adminUsername: admin
  adminPassword: passw0rd
  cookieAuthSecret: passw0rd
  allowAdminParty: false
  createAdminSecret: true
  persistentVolume:
    enabled: false
  initImage:
    pullPolicy: IfNotPresent
    tag: 1.28