version: v1
host: holzeis.par01.containers.appdomain.cloud
ingressSecret: holzeis
registry: richardholzeis/
env: prod
pullPolicy: Always
vapidPublicKey: QkdubDI0N21QdVcxYmhhbnZxeTJFWExWWEFjdFNJQk9lMzNUaURKODlCUzhTcjRBV2NxQ2Nqa3RKOGN1eGxMWnQtblo5bi1POHhwZFRKTVdCVnFZcXNz

couchdb:
  clusterSize: 1
  adminUsername: admin
  adminPassword: passw0rd
  cookieAuthSecret: passw0rd
  allowAdminParty: false
  createAdminSecret: true
  persistentVolume:
    enabled: false
  initImage:
    pullPolicy: IfNotPresent
    tag: 1.28