apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heckle.fullname" . }}-secret
type: Opaque
data:
  vapidPrivateKey: {{ .Values.vapid.privateKey | b64enc }}
  jsonWebTokenSecret: {{ .Values.server.jwt.secret | b64enc }}