apiVersion: v1
kind: Service
metadata:
  name: {{ include "heckle.uiname" . }}
  labels:
    {{- include "heckle.uiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "heckle.uiSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "heckle.servername" . }}
  labels:
    {{- include "heckle.serverLabels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.service.websocket.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "heckle.serverSelectorLabels" . | nindent 4 }}