apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heckle.fullname" . }}-secret
type: Opaque
data:
  vapidPrivateKey: {{ .Values.vapid.privateKey | b64enc }}
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  jsonWebTokenSecret: {{ randAlphaNum 32 | b64enc | quote}}
  