apiVersion: v1
kind: ConfigMap
metadata:
  name: heckle-config
  namespace: {{ .Release.Namespace }}
data:
  accounts.json: {{ .Files.Get "config/accounts.json" | quote }}
  environment.ts: |
    export const environment = {
      production: false,
      host: '{{ if .Values.ingress.secret }}https{{ else }}http{{ end }}://heckle.{{ .Values.ingress.host }}',
      api: 'api/v1',
      socket: '{{ if .Values.ingress.secret }}wss{{ else }}ws{{ end }}://heckle-ws.{{ .Values.ingress.host }}',
      publicKey: '{{ .Values.vapid.publicKey }}',
    };
  environment.prod.ts: |
    export const environment = {
      production: true,
      host: '{{ if .Values.ingress.secret }}https{{ else }}http{{ end }}://heckle.{{ .Values.ingress.host }}',
      api: 'api/v1',
      socket: '{{ if .Values.ingress.secret }}wss{{ else }}ws{{ end }}://heckle-ws.{{ .Values.ingress.host }}',
      publicKey: '{{ .Values.vapid.publicKey }}',
    };