apiVersion: apps/v1
kind: Deployment
metadata:
  name: heckle-client
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: heckle-client
  replicas: 1
  template:
    metadata:
      labels:
        app: heckle-client
        org: {{ .Release.Namespace }}
    spec:
      containers:
      - name: heckle-client
        image: {{ .Values.registry }}heckle-client:{{ .Values.version }}
        ports:
        - name: http
          containerPort: 4200
        {{ if eq .Values.env "prod" }}
        command: ["npm","run","start:prod"]
        {{ end }}
        volumeMounts:
        - mountPath: /usr/src/app/src/environments/environment.ts
          name: config
          subPath: environment.ts
        - mountPath: /usr/src/app/src/environments/environment.prod.ts
          name: config
          subPath: environment.prod.ts
      volumes:
      - name: config
        configMap:
          name: heckle-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heckle-server
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: heckle-server
  replicas: 1
  template:
    metadata:
      labels:
        app: heckle-server
    spec:
      containers:
      - name: heckle-server
        image: {{ .Values.registry }}heckle-server:{{ .Values.version }}
        ports:
        - name: http
          containerPort: 3000
        - name: websocket
          containerPort: 2000
        env:
        - name: COUCHDB_ADMIN_USER
          value: {{ .Values.couchdb.adminUsername }}
        - name: COUCHDB_ADMIN_PASSWORD
          value: {{ .Values.couchdb.adminPassword }}
        - name: COUCHDB_ENDPOINT
          value: {{ .Release.Name }}-couchdb.{{ .Release.Namespace }}
        - name: COUCHDB_PORT
          value: "5984"  
