apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.bluemix.net/websocket-services: "heckle-server"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  {{ if .Values.ingressSecret }}
  tls:
   - hosts:
     - heckle-ws.{{ .Values.host }}
     - heckle.{{ .Values.host }}
     secretName: {{ .Values.ingressSecret }}
  {{ end }}
  rules:
  - host: heckle.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: heckle-client
          servicePort: 4200
      - path: /api/v1
        backend:
          serviceName: heckle-server
          servicePort: 3000
  - host: heckle-ws.{{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: heckle-server
          servicePort: 2000
