apiVersion: v1
kind: Service
metadata:
  name: heckle-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: heckle-client
spec:
  selector:
    app: heckle-client
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200

