apiVersion: v1
kind: Service
metadata:
  name: heckle-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: heckle-client
spec:
  selector:
    app: heckle-client
  ports:
  - protocol: TCP
    port: 4200
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: heckle-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: heckle-server
spec:
  selector:
    app: heckle-server
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: http
  - name: websocket
    port: 2000
    targetPort: websocket
